# Generated by Django 4.2.4 on 2023-08-17 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalSpecies',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=20)),
                ('speciesImgUrl', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='background',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('backgroundImgUrl', models.URLField(blank=True, null=True)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('contentUrl', models.URLField(blank=True, null=True)),
                ('createdAt', models.DateTimeField()),
                ('updatedAt', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='LetterTemplate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('letterTemplateImgUrl', models.URLField(blank=True, null=True)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('death', models.CharField(choices=[('ACCIDENT', 'ACCIDENT'), ('OLD', 'OLD'), ('DIESASE', 'DISEASE'), ('EUTHANASIA', 'EUTHANASIA')], max_length=10)),
                ('category', models.CharField(choices=[('LETTER', 'LETTER'), ('MIND', 'MIND'), ('NORMAL', 'NORMAL')], max_length=10)),
                ('createdAt', models.DateTimeField()),
                ('updatedAt', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('taskNumber', models.IntegerField()),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userId', models.CharField(max_length=30)),
                ('userName', models.CharField(max_length=10)),
                ('alarm', models.BooleanField(default=True)),
                ('description', models.CharField(max_length=30)),
                ('taskCount', models.IntegerField(default=0)),
                ('star', models.IntegerField(default=0)),
                ('callBy', models.CharField(max_length=10)),
                ('animalName', models.CharField(max_length=10)),
                ('animalSpecies', models.CharField(max_length=30)),
                ('animalImgUrl', models.URLField(blank=True, null=True)),
                ('animalDeathDate', models.DateTimeField()),
                ('death', models.CharField(choices=[('ACCIDENT', 'ACCIDENT'), ('OLD', 'OLD'), ('DIESASE', 'DISEASE'), ('EUTHANASIA', 'EUTHANASIA')], max_length=10)),
                ('animalAge', models.IntegerField()),
                ('AnimalSpeciesId', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='petmourning.animalspecies')),
                ('backgroundId', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='petmourning.background')),
                ('letterTemplateId', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='petmourning.lettertemplate')),
            ],
        ),
        migrations.CreateModel(
            name='Recomment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('contentUrl', models.URLField(blank=True, null=True)),
                ('createdAt', models.DateTimeField()),
                ('updatedAt', models.DateTimeField()),
                ('commentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petmourning.comment')),
                ('postId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petmourning.post')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomments_by_user', to='petmourning.user')),
                ('userTagId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomments_by_tag', to='petmourning.user')),
            ],
        ),
        migrations.CreateModel(
            name='PostPicture',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contentUrl', models.URLField(blank=True, null=True)),
                ('postId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petmourning.post')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petmourning.user'),
        ),
        migrations.AddField(
            model_name='comment',
            name='postId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petmourning.post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petmourning.user'),
        ),
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petmourning.post')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petmourning.user')),
            ],
            options={
                'unique_together': {('userId', 'postId')},
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('contentUrl', models.URLField(blank=True, null=True)),
                ('postOut', models.BooleanField(default=False)),
                ('emotion', models.CharField(choices=[('BAD', 'BAD'), ('SOSO', 'SOSO'), ('GOOD', 'GOOD')], max_length=10)),
                ('createdAt', models.DateTimeField()),
                ('questionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petmourning.question')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petmourning.user')),
            ],
            options={
                'unique_together': {('userId', 'questionId')},
            },
        ),
    ]
