# Generated by Django 4.2.4 on 2023-09-01 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petmourning', '0002_alter_mailbox_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailbox',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='petmourning.post'),
        ),
    ]
