# Generated by Django 4.2.5 on 2023-09-20 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petmourning', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='AnimalSpeciesId',
        ),
        migrations.RemoveField(
            model_name='user',
            name='backgroundId',
        ),
        migrations.RemoveField(
            model_name='user',
            name='letterTemplateId',
        ),
    ]
