# Generated by Django 4.2.5 on 2023-09-20 15:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('petmourning', '0002_remove_user_animalspeciesid_remove_user_backgroundid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='animalDeathDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
