# Generated by Django 4.2.5 on 2023-09-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petmourning', '0003_alter_user_animaldeathdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='animalAge',
            field=models.IntegerField(null=True),
        ),
    ]
