# Generated by Django 5.0a1 on 2023-10-02 03:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petmourning', '0004_alter_user_animalage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='animalDeathDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
